# Generated by Django 4.0.1 on 2022-02-17 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=200)),
                ('emp_code', models.CharField(max_length=200)),
                ('Mobile', models.CharField(max_length=200)),
                ('Position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_register.position')),
            ],
        ),
    ]
